ci:
- all:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

build_system:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - meson_options.txt
      - '**/meson.build'

sigutils:
- all:
  - changed-files:
    - any-glob-to-any-file: 'src/**'
    - all-globs-to-all-files: '!**/meson.build'

documentation:
- all:
  - changed-files:
    - any-glob-to-any-file: 'doc/**'
    - all-globs-to-all-files: '!**/meson.build'

tests:
- all:
  - changed-files:
    - any-glob-to-any-file: 'tests/**'
    - all-globs-to-all-files: '!**/meson.build'
